AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # API Gateway defined in a separate swagger document
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionUri: swagger.yml
      Variables:
      # Stage variable needed in order to get the resulting name of the Lambda Function
      # after deployment
        LambdaFunctionName: !Ref LambdaFunction
  # Lambda function definition
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: built/api_backend.handler
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBFullAccess
      CodeUri: ./
      Timeout: 10
      Environment:
        Variables:
          # DynamoDB Table name is given to Lambda function as an environment variable
          TABLE_NAME: !Ref DynamoDBTable
      # These events will call the Lambda
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref ApiGatewayApi
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGatewayApi
  # Add necessary permissions for API Gateway to invoke Lambda function
  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: 
        Fn::GetAtt: 
          - LambdaFunction
          - Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ':'
          - !Ref AWS::AccountId
          - ':'
          - !Ref ApiGatewayApi
          - '/*/*/*'
  # Defines a quite simple DynamoDB table
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions:
        - AttributeName: "timeFrom"
          AttributeType: S
      KeySchema: 
        - AttributeName: "timeFrom"
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: "reservations"
# Outputs of this CloudFormation template
# Returns the resulting API Gateway endpoint URL
Outputs:
  ApiUrl:
    Description: URL of the API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref ApiGatewayApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/prod'